begin;
set local search_path=public,extensions,pg_temp;
select no_plan();
insert into auth.users(id,email,email_confirmed_at)
select ('99000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'u1-'||n||'@example.invalid',now() from generate_series(1,8) n;
insert into auth.identities(id,user_id,provider_id,provider,identity_data)
select gen_random_uuid(),id,id::text,'google',jsonb_build_object('email',email,'email_verified',true)
from auth.users where email like 'u1-%@example.invalid';
insert into public.profiles(id,full_name,email,role,status,approved_at)
values('99000000-0000-4000-8000-000000000001','Roster Admin','u1-1@example.invalid','admin','approved',now());
insert into public.profiles(id,full_name,email,student_id,role,status,program,required_hours,approved_at,approved_by)
select id,'Existing Student',email,'U1-EXIST-'||right(id::text,1),'student',
  case right(id::text,1) when '2' then 'approved' when '3' then 'pending' else 'rejected' end,
  'BS Information Technology',486,case when right(id::text,1)='2' then now() end,
  case when right(id::text,1)='2' then '99000000-0000-4000-8000-000000000001'::uuid end
from auth.users where id in ('99000000-0000-4000-8000-000000000002','99000000-0000-4000-8000-000000000003','99000000-0000-4000-8000-000000000004');
select ok((select relrowsecurity from pg_class where oid='private.authorized_students'::regclass),'roster RLS enabled');
select is((select count(*)::integer from pg_policy where polrelid='private.authorized_students'::regclass),0,'no direct roster policies');
set local role authenticated;
select set_config('request.jwt.claim.sub','99000000-0000-4000-8000-000000000001',true);
select lives_ok($$select public.admin_add_authorized_student(' u1-allowed ',' Reference, Name ')$$,'Admin adds normalized ID');
select throws_ok($$select public.admin_add_authorized_student('U1-ALLOWED','Other, Name')$$,'23505','STUDENT_ID_ALREADY_AUTHORIZED','duplicate does not overwrite');
select throws_ok($$select public.admin_add_authorized_student('bad id',null)$$,'22023','INVALID_ROSTER_DETAILS','format validation');
select throws_ok($$select public.admin_add_authorized_student('U1-BAD',repeat('x',101))$$,'22023','INVALID_ROSTER_DETAILS','name bounded');
select is(public.admin_authorized_students('reference',25,null)->0->>'student_id','U1-ALLOWED','name search');
select is(public.admin_authorized_students('U1-ALLOWED',25,null)->0->>'registration_state','not_registered','trusted unregistered state');
select is(public.admin_authorized_students('U1-ALLOWED',25,null)->0->>'created_by',auth.uid()::text,'server creator');
select throws_ok($$select public.admin_authorized_students(null,101,null)$$,'22023','INVALID_ROSTER_QUERY','bounded reads');
select throws_ok($$select public.admin_authorized_students(null,null,null)$$,'22023','INVALID_ROSTER_QUERY','null cannot unbound reads');
select throws_ok($$select public.admin_set_authorized_student_active('U1-ALLOWED',null)$$,'22023','INVALID_ROSTER_DETAILS','null activation rejected');
select throws_ok($$select * from private.authorized_students$$,'42501',null,'Admin direct read denied');
select throws_ok($$insert into private.authorized_students(student_id) values('U1-DIRECT')$$,'42501',null,'Admin direct insert denied');
select throws_ok($$update private.authorized_students set is_active=false$$,'42501',null,'Admin direct update denied');
select throws_ok($$delete from private.authorized_students$$,'42501',null,'Admin direct delete denied');
select lives_ok($$select public.admin_set_authorized_student_active('U1-ALLOWED',false)$$,'Admin deactivates');
select set_config('request.jwt.claim.sub','99000000-0000-4000-8000-000000000005',true);
select throws_ok($$select public.complete_student_registration('New Student','U1-MISSING','Reference')$$,'P0001','STUDENT_IDENTITY_NOT_ELIGIBLE','missing ID rejected');
select throws_ok($$select public.complete_student_registration('New Student','U1-ALLOWED','Reference')$$,'P0001','STUDENT_IDENTITY_NOT_ELIGIBLE','inactive gets same error');
select is((select count(*)::integer from public.profiles),0,'no partial profile');
select throws_ok($$select public.complete_student_registration('','U1-ALLOWED','Reference')$$,'23514','INVALID_REGISTRATION_DETAILS','invalid name rejected');
select set_config('request.jwt.claim.sub','99000000-0000-4000-8000-000000000001',true);
select lives_ok($$select public.admin_set_authorized_student_active('U1-ALLOWED',true)$$,'reactivation');
select set_config('request.jwt.claim.sub','99000000-0000-4000-8000-000000000005',true);
select lives_ok($$select public.complete_student_registration(' New Student ',' u1-allowed ','Reference')$$,'authorized registration after failed attempt');
select ok((select role='student' and status='pending' and program='BS Information Technology' and required_hours=486 and email='u1-5@example.invalid' and approved_at is null and approved_by is null from public.profiles where id=auth.uid()),'trusted authority fields never auto-approve');
select throws_ok($$select public.complete_student_registration('Other','U1-OTHER','Reference')$$,'P0001','PROFILE_ALREADY_EXISTS','same account cannot register again');
select set_config('request.jwt.claim.sub','99000000-0000-4000-8000-000000000006',true);
select throws_ok($$select public.complete_student_registration('Other','U1-ALLOWED','Reference')$$,'23505','STUDENT_ID_ALREADY_REGISTERED','second account cannot claim');
select throws_ok($$select public.complete_student_registration('Other','U1-ALLOWED','admin','Reference')$$,'42883',null,'no authority argument');
select set_config('request.jwt.claim.sub','99000000-0000-4000-8000-000000000001',true);
select is(public.admin_authorized_students('U1-ALLOWED',25,null)->0->>'registration_state','pending','pending derived');
select lives_ok($$select public.review_student('99000000-0000-4000-8000-000000000005','rejected')$$,'existing review remains');
select is(public.admin_authorized_students('U1-ALLOWED',25,null)->0->>'registration_state','rejected','rejected derived');
select lives_ok($$select public.admin_set_authorized_student_active('U1-ALLOWED',false)$$,'deactivate claimed');
select is((select status from public.profiles where student_id='U1-ALLOWED'),'rejected','deactivation leaves profile unchanged');
select lives_ok($$select public.admin_set_authorized_student_active('U1-ALLOWED',true)$$,'reactivate cannot release claim');
select set_config('request.jwt.claim.sub','99000000-0000-4000-8000-000000000006',true);
select throws_ok($$select public.complete_student_registration('Other','U1-ALLOWED','Reference')$$,'23505','STUDENT_ID_ALREADY_REGISTERED','rejected still claimed');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','99000000-0000-4000-8000-000000000002',true);
select throws_ok($$select public.admin_authorized_students(null,25,null)$$,'42501','APPROVED_ADMIN_REQUIRED','non-Admin 2 denied');
select throws_ok($$select public.admin_add_authorized_student('U1-FORGED',null)$$,'42501','APPROVED_ADMIN_REQUIRED','non-Admin 2 denied');
select throws_ok($$select public.admin_set_authorized_student_active('U1-ALLOWED',true)$$,'42501','APPROVED_ADMIN_REQUIRED','non-Admin 2 denied');
select throws_ok($$select * from private.authorized_students$$,'42501',null,'non-Admin 2 direct access denied');
select throws_ok($$insert into private.authorized_students(student_id) values('U1-FORGED')$$,'42501',null,'non-Admin 2 direct access denied');
select throws_ok($$update private.authorized_students set is_active=true$$,'42501',null,'non-Admin 2 direct access denied');
select throws_ok($$delete from private.authorized_students$$,'42501',null,'non-Admin 2 direct access denied');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','99000000-0000-4000-8000-000000000003',true);
select throws_ok($$select public.admin_authorized_students(null,25,null)$$,'42501','APPROVED_ADMIN_REQUIRED','non-Admin 3 denied');
select throws_ok($$select public.admin_add_authorized_student('U1-FORGED',null)$$,'42501','APPROVED_ADMIN_REQUIRED','non-Admin 3 denied');
select throws_ok($$select public.admin_set_authorized_student_active('U1-ALLOWED',true)$$,'42501','APPROVED_ADMIN_REQUIRED','non-Admin 3 denied');
select throws_ok($$select * from private.authorized_students$$,'42501',null,'non-Admin 3 direct access denied');
select throws_ok($$insert into private.authorized_students(student_id) values('U1-FORGED')$$,'42501',null,'non-Admin 3 direct access denied');
select throws_ok($$update private.authorized_students set is_active=true$$,'42501',null,'non-Admin 3 direct access denied');
select throws_ok($$delete from private.authorized_students$$,'42501',null,'non-Admin 3 direct access denied');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','99000000-0000-4000-8000-000000000004',true);
select throws_ok($$select public.admin_authorized_students(null,25,null)$$,'42501','APPROVED_ADMIN_REQUIRED','non-Admin 4 denied');
select throws_ok($$select public.admin_add_authorized_student('U1-FORGED',null)$$,'42501','APPROVED_ADMIN_REQUIRED','non-Admin 4 denied');
select throws_ok($$select public.admin_set_authorized_student_active('U1-ALLOWED',true)$$,'42501','APPROVED_ADMIN_REQUIRED','non-Admin 4 denied');
select throws_ok($$select * from private.authorized_students$$,'42501',null,'non-Admin 4 direct access denied');
select throws_ok($$insert into private.authorized_students(student_id) values('U1-FORGED')$$,'42501',null,'non-Admin 4 direct access denied');
select throws_ok($$update private.authorized_students set is_active=true$$,'42501',null,'non-Admin 4 direct access denied');
select throws_ok($$delete from private.authorized_students$$,'42501',null,'non-Admin 4 direct access denied');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','99000000-0000-4000-8000-000000000005',true);
select throws_ok($$select public.admin_authorized_students(null,25,null)$$,'42501','APPROVED_ADMIN_REQUIRED','non-Admin 5 denied');
select throws_ok($$select public.admin_add_authorized_student('U1-FORGED',null)$$,'42501','APPROVED_ADMIN_REQUIRED','non-Admin 5 denied');
select throws_ok($$select public.admin_set_authorized_student_active('U1-ALLOWED',true)$$,'42501','APPROVED_ADMIN_REQUIRED','non-Admin 5 denied');
select throws_ok($$select * from private.authorized_students$$,'42501',null,'non-Admin 5 direct access denied');
select throws_ok($$insert into private.authorized_students(student_id) values('U1-FORGED')$$,'42501',null,'non-Admin 5 direct access denied');
select throws_ok($$update private.authorized_students set is_active=true$$,'42501',null,'non-Admin 5 direct access denied');
select throws_ok($$delete from private.authorized_students$$,'42501',null,'non-Admin 5 direct access denied');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','99000000-0000-4000-8000-000000000006',true);
select throws_ok($$select public.admin_authorized_students(null,25,null)$$,'42501','APPROVED_ADMIN_REQUIRED','non-Admin 6 denied');
select throws_ok($$select public.admin_add_authorized_student('U1-FORGED',null)$$,'42501','APPROVED_ADMIN_REQUIRED','non-Admin 6 denied');
select throws_ok($$select public.admin_set_authorized_student_active('U1-ALLOWED',true)$$,'42501','APPROVED_ADMIN_REQUIRED','non-Admin 6 denied');
select throws_ok($$select * from private.authorized_students$$,'42501',null,'non-Admin 6 direct access denied');
select throws_ok($$insert into private.authorized_students(student_id) values('U1-FORGED')$$,'42501',null,'non-Admin 6 direct access denied');
select throws_ok($$update private.authorized_students set is_active=true$$,'42501',null,'non-Admin 6 direct access denied');
select throws_ok($$delete from private.authorized_students$$,'42501',null,'non-Admin 6 direct access denied');
reset role;
set local role anon;
select throws_ok($$select public.admin_authorized_students(null,25,null)$$,'42501',null,'anonymous cannot list');
select throws_ok($$select public.admin_add_authorized_student('U1-FORGED',null)$$,'42501',null,'anonymous cannot add');
select throws_ok($$select public.admin_set_authorized_student_active('U1-ALLOWED',true)$$,'42501',null,'anonymous cannot activate');
select throws_ok($$select * from private.authorized_students$$,'42501',null,'anonymous direct read denied');
reset role;
select ok(exists(select 1 from pg_constraint where conname='profiles_student_id_key'),'profile UNIQUE defense preserved');
select * from finish();
rollback;
