begin;
\ir ../helpers/legacy-attendance.inc
set local search_path=public,extensions,pg_temp;
select no_plan();
insert into auth.users(id,email,email_confirmed_at)
select ('99100000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'u11-'||n||'@example.invalid',now() from generate_series(1,8) n;
insert into auth.identities(id,user_id,provider_id,provider,identity_data)
select gen_random_uuid(),id,id::text,'google',jsonb_build_object('email',email,'email_verified',true) from auth.users where email like 'u11-%@example.invalid';
insert into public.profiles(id,full_name,email,role,status,approved_at) values('99100000-0000-4000-8000-000000000001','Admin','u11-1@example.invalid','admin','approved',now());
select is(to_regprocedure('public.complete_student_registration(text,text)'),null,'old overload absent');
select is(private.normalize_last_name('  De   La CRUZ  '),'de la cruz','case and repeated spaces normalized');
select is(private.normalize_last_name(U&'Pen\0303a'),private.normalize_last_name('Peña'),'NFC equivalence');
select isnt(private.normalize_last_name('Pena'),private.normalize_last_name('Peña'),'accents not stripped');
select isnt(private.normalize_last_name('De-la Cruz'),private.normalize_last_name('De la Cruz'),'punctuation not stripped');
select is(private.roster_last_name('Ambiguous Plain Name'),null,'no guessed surname');
select is(private.roster_last_name('Family, Given, Suffix'),null,'multiple commas rejected');
select is(private.roster_last_name('Family, '),null,'given name required');
set local role authenticated;
select set_config('request.jwt.claim.sub','99100000-0000-4000-8000-000000000001',true);
select throws_ok($$select public.admin_add_authorized_student('U11-A')$$,'22023','INVALID_ROSTER_DETAILS','name mandatory even through old default');
select throws_ok($$select public.admin_add_authorized_student('U11-A','')$$,'22023','INVALID_ROSTER_DETAILS','blank name denied');
select throws_ok($$select public.admin_add_authorized_student('U11-A','Ambiguous Name')$$,'22023','INVALID_ROSTER_DETAILS','format required');
select lives_ok($$select public.admin_add_authorized_student('U11-A','De La Cruz, Maria A.')$$,'valid required name');
select lives_ok($$select public.admin_add_authorized_student('U11-B','Peña, Juan')$$,'Unicode name');
select is((public.admin_authorized_students('U11-A',25,null)->0->>'verification_ready')::boolean,true,'Admin sees ready');
select set_config('request.jwt.claim.sub','99100000-0000-4000-8000-000000000002',true);
select throws_ok($$select public.complete_student_registration('Student','U11-A')$$,'42883',null,'two-argument bypass unavailable');
select throws_ok($$select public.complete_student_registration('Student','U11-A','De La Cruzz')$$,'P0001','STUDENT_IDENTITY_NOT_ELIGIBLE','generic mismatch; no eligibility detail');
select throws_ok($$select public.complete_student_registration('Student','U11-NONE','De La Cruz')$$,'P0001','STUDENT_IDENTITY_NOT_ELIGIBLE','generic mismatch; no eligibility detail');
select throws_ok($$select public.complete_student_registration('Student','U11-A','')$$,'P0001','STUDENT_IDENTITY_NOT_ELIGIBLE','generic mismatch; no eligibility detail');
select throws_ok($$select public.complete_student_registration('Student','U11-A',null)$$,'P0001','STUDENT_IDENTITY_NOT_ELIGIBLE','generic mismatch; no eligibility detail');
select is((select count(*)::integer from public.profiles),0,'failures create no profile');
select set_config('request.jwt.claim.sub','99100000-0000-4000-8000-000000000001',true);
select is(jsonb_array_length(public.admin_students(account_status=>'pending')),0,'failures create no Admin pending request');
select public.admin_set_authorized_student_active('U11-A',false);
select set_config('request.jwt.claim.sub','99100000-0000-4000-8000-000000000002',true);
select throws_ok($$select public.complete_student_registration('Student','U11-A','De La Cruz')$$,'P0001','STUDENT_IDENTITY_NOT_ELIGIBLE','inactive same generic failure');
select set_config('request.jwt.claim.sub','99100000-0000-4000-8000-000000000001',true);
select public.admin_set_authorized_student_active('U11-A',true);
select set_config('request.jwt.claim.sub','99100000-0000-4000-8000-000000000002',true);
select lives_ok($$select public.complete_student_registration('Display Name','u11-a','  DE   la  CRUZ ')$$,'correct normalized surname creates pending');
select ok((select status='pending' and role='student' and full_name='Display Name' and email='u11-2@example.invalid' and required_hours=486 from public.profiles where id=auth.uid()),'trusted profile preserved');
select set_config('request.jwt.claim.sub','99100000-0000-4000-8000-000000000003',true);
select throws_ok($$select public.complete_student_registration('Other','U11-A','De La Cruz')$$,'23505','STUDENT_ID_ALREADY_REGISTERED','no second claim');
select lives_ok($$select public.complete_student_registration('Juan','U11-B',U&'Pen\0303a')$$,'Unicode normalization succeeds in RPC');
select throws_ok($$select public.admin_update_authorized_student_name('U11-A','Other, Name')$$,'42501','APPROVED_ADMIN_REQUIRED','student correction denied');
select throws_ok($$select * from private.authorized_students$$,'42501',null,'no student roster reads');
select throws_ok($$select public.admin_authorized_students()$$,'42501','APPROVED_ADMIN_REQUIRED','no enumeration');
select set_config('request.jwt.claim.sub','99100000-0000-4000-8000-000000000001',true);
select is((public.admin_students(target_uid=>'99100000-0000-4000-8000-000000000002')->0->>'roster_eligible')::boolean,true,'pending green');
select public.admin_set_authorized_student_active('U11-A',false);
select is((public.admin_students(target_uid=>'99100000-0000-4000-8000-000000000002')->0->>'roster_eligible')::boolean,false,'pending red after deactivation');
select throws_ok($$select public.review_student('99100000-0000-4000-8000-000000000002','approved')$$,'P0001','ROSTER_APPROVAL_NOT_ELIGIBLE','direct approval denied');
select public.admin_set_authorized_student_active('U11-A',true);
select lives_ok($$select public.review_student('99100000-0000-4000-8000-000000000002','approved')$$,'reactivation allows approval');
select public.admin_set_authorized_student_active('U11-A',false);
select lives_ok($$select public.admin_update_authorized_student_name('U11-A','Corrected, Reference')$$,'claimed reference correction allowed');
select is((select full_name from public.profiles where student_id='U11-A'),'Display Name','correction does not rename profile');
select is((select status from public.profiles where student_id='U11-A'),'approved','approved access not revoked');
select public.admin_set_authorized_student_active('U11-B',false);
select lives_ok($$select public.review_student('99100000-0000-4000-8000-000000000003','rejected')$$,'reject remains available while ineligible');
select set_config('request.jwt.claim.sub','99100000-0000-4000-8000-000000000002',true);
select lives_ok($$select pg_temp.legacy_time_in()$$,'approved inactive-roster student still times in');
select lives_ok($$select public.activity_prepare('99100000-0000-4000-8000-000000000099',null)$$,'approved inactive-roster student may prepare activity');
select lives_ok($$select pg_temp.legacy_time_out()$$,'approved inactive-roster student still times out');
reset role;
insert into private.authorized_students(student_id,expected_name) values('U11-LEGACY','Ambiguous Legacy');
set local role authenticated;
select set_config('request.jwt.claim.sub','99100000-0000-4000-8000-000000000004',true);
select throws_ok($$select public.complete_student_registration('Legacy','U11-LEGACY','Legacy')$$,'P0001','STUDENT_IDENTITY_NOT_ELIGIBLE','unresolved legacy entry fails closed');
select set_config('request.jwt.claim.sub','99100000-0000-4000-8000-000000000001',true);
select is((public.admin_authorized_students('U11-LEGACY')->0->>'verification_ready')::boolean,false,'legacy correction flag');
select throws_ok($$select public.admin_update_authorized_student_name('U11-LEGACY','')$$,'22023','INVALID_ROSTER_DETAILS','invalid correction rejected');
select lives_ok($$select public.admin_update_authorized_student_name('U11-LEGACY','Legacy, Student')$$,'Admin repairs ambiguous row');
select set_config('request.jwt.claim.sub','99100000-0000-4000-8000-000000000004',true);
select lives_ok($$select public.complete_student_registration('Legacy Student','U11-LEGACY','Legacy')$$,'corrected row can register');
reset role;
select is((select count(*)::integer from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='complete_student_registration'),1,'only one registration signature');
select * from finish();
rollback;
