import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile,writeFile } from 'node:fs/promises'
import { prepareJournalExport,buildJournalPdf,exportFilename,EXPORT_LIMITS } from '../src/services/journalExportModel.js'
import { createJournalExportController,journalExportState } from '../src/services/journalExportController.js'
import { printJournalReport,JOURNAL_PRINT_CSS } from '../src/services/journalPrint.js'
import { convertJournalImage } from '../src/services/journalExportImages.js'
import { generateJournalPdf } from '../src/services/journalPdf.js'
const tiny='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aX1sAAAAASUVORK5CYII='
const text='  Installed RAM.\nChecked résumé and señor records. Exact CASE!  '
function report(){return {schemaVersion:1,student:{fullName:'Synthetic Student',studentId:'S/01',program:'BS Information Technology',requiredHours:486},range:{from:'2026-10-04',to:'2026-10-04',timezone:'Asia/Manila'},days:[{date:'2026-10-04',completedSeconds:3600.5,activities:[{sourceIndex:0,createdAt:'2026-10-04T00:00:00Z',category:'Hardware / Maintenance',description:text,edited:true}],sessions:[{ordinal:1,timeIn:'2026-10-04T00:00:00Z',timeOut:'2026-10-04T01:00:00.500Z'},{ordinal:2,timeIn:'2026-10-04T15:00:00Z',timeOut:null}]}],selectedRangeCompletedSeconds:3600.5,lifetimeCompletedSeconds:7200,internal:{sources:[{id:'PRIVATE-ID',revision:1,proofPath:'PRIVATE-PATH',attendanceSessionId:'PRIVATE-SESSION'}]}}}
const options=(extra={})=>({readProof:async()=>new Blob(['synthetic'],{type:'image/png'}),convertImage:async()=>({data:tiny,width:640,height:320,bytes:100}),...extra})
test('safe deterministic Daily and Range filenames',()=>{const r=report();assert.equal(exportFilename(r),'OJT-Journal_S_01_2026-10-04.pdf');r.range.to='2026-10-05';assert.equal(exportFilename(r),'OJT-Journal_S_01_2026-10-04_to_2026-10-05.pdf')})
test('exact Unicode and linebreak descriptions preserved; internals excluded',async()=>{const p=await prepareJournalExport(report(),options());assert.equal(p.days[0].activities[0].description,text);assert.doesNotMatch(JSON.stringify(p),/PRIVATE-ID|PRIVATE-PATH|PRIVATE-SESSION/);assert.equal(p.student.requiredHours,486)})
test('distinct authoritative selected/total/daily hours and Session 1/2',async()=>{const p=await prepareJournalExport(report(),options());assert.equal(p.selectedHours,'1h 00m');assert.equal(p.totalHours,'2h 00m');assert.equal(p.days[0].sessions[1].timeOut,'Ongoing');assert.equal(p.days[0].sessions[0].ordinal,1)})
test('overnight Time Out retains actual date',async()=>{const r=report();r.days[0].sessions[1].timeOut='2026-10-04T17:00:00Z';assert.match((await prepareJournalExport(r,options())).days[0].sessions[1].timeOut,/October 5, 2026/)})
test('photo option OFF never reads or converts proof',async()=>{let reads=0;const p=await prepareJournalExport(report(),options({includePhotos:false,readProof:async()=>{reads++}}));assert.equal(reads,0);assert.equal(p.days[0].activities[0].photo,null)})
test('photo option ON uses exact proof association',async()=>{const paths=[];await prepareJournalExport(report(),options({readProof:async path=>{paths.push(path);return new Blob(['x'])}}));assert.deepEqual(paths,['PRIVATE-PATH'])})
test('many photos prepared sequentially and in activity order',async()=>{const r=report();r.days[0].activities=Array.from({length:8},(_,i)=>({...r.days[0].activities[0],sourceIndex:i,description:`Task ${i}`}));r.internal.sources=Array.from({length:8},(_,i)=>({proofPath:`proof${i}`}));let active=0,max=0;const p=await prepareJournalExport(r,options({readProof:async()=>{active++;max=Math.max(active,max);await new Promise(resolve=>setImmediate(resolve));active--;return new Blob(['x'])}}));assert.equal(max,1);assert.deepEqual(p.days[0].activities.map(a=>a.description),Array.from({length:8},(_,i)=>`Task ${i}`))})
test('unavailable image continues report with neutral note',async()=>{const p=await prepareJournalExport(report(),options({readProof:async()=>{throw Error('PRIVATE-PATH RAW TOKEN')}}));assert.equal(p.unavailablePhotos,1);assert.equal(p.days[0].activities[0].photoNote,'Activity proof photo unavailable');assert.equal(p.days[0].activities[0].description,text)})
test('historical/no-proof and attendance-only/empty dates remain valid',async()=>{const r=report();r.internal.sources=[];assert.equal((await prepareJournalExport(r,options())).days[0].activities[0].photoNote,'No proof photo available');r.range.to='2026-10-05';r.days.push({...r.days[0],date:'2026-10-05',activities:[]});assert.equal((await prepareJournalExport(r,options())).days[1].sessions.length,2)})
test('large report explicitly fails instead of silently truncating',async()=>{const r=report();r.days[0].activities=Array.from({length:EXPORT_LIMITS.activities+1},()=>r.days[0].activities[0]);await assert.rejects(prepareJournalExport(r,options({includePhotos:false})),/EXPORT_TOO_LARGE/)})
test('PDF definition A4, fit photos and exact literal text, no active links',async()=>{const p=await prepareJournalExport(report(),options()),definition=buildJournalPdf(p);assert.equal(definition.pageSize,'A4');assert.ok(JSON.stringify(definition.content).includes(JSON.stringify(text).slice(1,-1)));assert.ok(definition.content.some(n=>n.stack?.some(child=>child.image&&child.fit[0]===440)));assert.doesNotMatch(JSON.stringify(definition),/PRIVATE-PATH|PRIVATE-ID|latitude|selfie/);assert.equal(definition.footer(1,2).columns[1].text,'1 / 2')})
function controllerFixture(extra={}){let current=report(),key='student';const state=journalExportState(),calls=[];const c=createJournalExportController(state,{currentReport:()=>current,identity:()=>key,...options(),validateReport:async()=>current,pdf:async p=>{calls.push(['pdf',p]);return new Blob(['%PDF-test'])},print:async p=>calls.push(['print',p]),save:async(b,n)=>calls.push(['save',n]),...extra});return {state,c,calls,change:()=>{current=report()},account:()=>{key='other'}}}
test('genuine generation adapter invoked; duplicate clicks blocked',async()=>{let resolve;const f=controllerFixture({pdf:()=>new Promise(r=>resolve=r)});const pending=f.c.run('pdf',false);await new Promise(r=>setImmediate(r));await f.c.run('pdf',false);resolve(new Blob(['%PDF']));await pending;assert.equal(f.calls.filter(c=>c[0]==='save').length,1)})
test('Print waits for requested proof preparation',async()=>{let resolve;const f=controllerFixture({readProof:()=>new Promise(r=>resolve=r)});const pending=f.c.run('print',true);assert.equal(f.calls.length,0);resolve(new Blob(['x']));await pending;assert.equal(f.calls[0][0],'print');assert.ok(f.calls[0][1].days[0].activities[0].photo)})
test('scope change/cancel/account change prevent stale output',async()=>{for(const kind of ['cancel','scope','account']){let resolve;const f=controllerFixture({pdf:()=>new Promise(r=>resolve=r)});const pending=f.c.run('pdf',false);await new Promise(r=>setImmediate(r));if(kind==='cancel')f.c.cancel();else if(kind==='scope')f.change();else f.account();resolve(new Blob(['%PDF']));await pending;assert.equal(f.calls.length,0)}})
test('revision change aborts output and asks refresh',async()=>{const f=controllerFixture({validateReport:async()=>{const r=report();r.internal.sources[0].revision=2;return r}});await f.c.run('pdf',false);assert.match(f.state.error,/Records changed/);assert.equal(f.calls.length,0)})
test('dependency and fonts lazy imported, UI photos default checked and no Word',async()=>{const pdf=await readFile('src/services/journalPdf.js','utf8'),view=await readFile('src/views/student/JournalView.vue','utf8');assert.match(pdf,/import\('pdfmake\/build\/pdfmake.js'\)/);assert.match(pdf,/import\('pdfmake\/build\/vfs_fonts.js'\)/);assert.match(view,/includePhotos: true/);assert.match(view,/Download PDF/);assert.match(view,/Download Word/);assert.doesNotMatch(await readFile('src/services/journalExport.js','utf8'),/getPublicUrl|createSignedUrl|functions\.invoke|https:\/\/|Groq|Cloudflare/i)})
test('local conversion scales aspect ratio and revokes decode URL',async()=>{
 const originals={Image:globalThis.Image,document:globalThis.document},url={create:URL.createObjectURL,revoke:URL.revokeObjectURL};let revoked=0,canvas
 try{globalThis.Image=class{naturalWidth=3200;naturalHeight=1600;set src(_){queueMicrotask(()=>this.onload())}};globalThis.document={createElement(){canvas={getContext:()=>({fillRect(){},drawImage(){}}),toDataURL:()=>tiny.replace('image/png','image/jpeg')};return canvas}};URL.createObjectURL=()=> 'blob:decode';URL.revokeObjectURL=()=>revoked++;const result=await convertJournalImage(new Blob(['x']));assert.equal(result.width,1600);assert.equal(result.height,800);assert.equal(revoked,1)}finally{globalThis.Image=originals.Image;globalThis.document=originals.document;URL.createObjectURL=url.create;URL.revokeObjectURL=url.revoke}
})
function fakeDocument(){
 const all=[],handlers=new Map();let printed=0,removed=0
 function el(tag){const n={tag,children:[],style:{},textContent:'',appendChild(child){this.children.push(child)},setAttribute(){},remove(){removed++}};if(tag==='img')Object.defineProperty(n,'src',{set(v){n.value=v;queueMicrotask(()=>n.onload())}});all.push(n);return n}
 const child={body:el('body'),head:el('head'),createElement:el,fonts:{ready:Promise.resolve()}},win={addEventListener(n,fn){handlers.set(n,fn)},removeEventListener(n){handlers.delete(n)},focus(){},print(){printed++;handlers.get('afterprint')()}}
 const parent={body:el('parent'),createElement(tag){const n=el(tag);n.contentDocument=child;n.contentWindow=win;return n}}
 return {parent,all,printed:()=>printed,removed:()=>removed}
}
test('isolated Print uses literal nodes, waits images and excludes shell/actions',async()=>{const f=fakeDocument(),p=await prepareJournalExport(report(),options());await printJournalReport(p,new AbortController().signal,f.parent);assert.equal(f.printed(),1);assert.equal(f.removed(),1);assert.ok(f.all.some(n=>n.textContent===text));assert.ok(f.all.some(n=>n.tag==='img'));assert.ok(!f.all.some(n=>n.tag==='button'||n.tag==='nav'));assert.match(JOURNAL_PRINT_CSS,/size:A4 portrait/);assert.match(JOURNAL_PRINT_CSS,/white-space:pre-wrap/)})
test('real pdfmake produces genuine PDF and rendered QA artifact',async()=>{
 const r=report();r.range.to='2026-10-05';r.days[0].activities=Array.from({length:12},(_,i)=>({...r.days[0].activities[0],description:`Activity ${i+1}: ${text}\nCompleted a recorded equipment check.`}));r.internal.sources=[]
 r.days.push({date:'2026-10-05',activities:[],sessions:[],completedSeconds:0})
 const p=await prepareJournalExport(r,options({includePhotos:false})),data='data:image/png;base64,'+(await readFile(new URL('./helpers/journalExportProof.png', import.meta.url))).toString('base64');p.days[0].activities[0].photo={data,width:640,height:320,bytes:5000}
 const pdf=await generateJournalPdf(p),buffer=Buffer.from(await pdf.arrayBuffer());assert.equal(buffer.subarray(0,5).toString(),'%PDF-');assert.ok(buffer.length>5000);await writeFile('/tmp/dtr-u64d-synthetic.pdf',buffer)
})
test('unsupported glyphs fail visibly instead of losing source text',async()=>{const p=await prepareJournalExport(report(),options({includePhotos:false}));p.days[0].activities[0].description='日本語';await assert.rejects(generateJournalPdf(p),/PDF_UNSUPPORTED_TEXT/)})
test('sparse Date Range retains attendance and reports empty-day count compactly',async()=>{const r=report();r.range.to='2026-10-05';r.days.push({date:'2026-10-05',activities:[],sessions:[],completedSeconds:0});const p=await prepareJournalExport(r,options({includePhotos:false}));assert.equal(p.days.length,2);assert.equal(p.days[1].activities.length,0);assert.ok(JSON.stringify(buildJournalPdf(p).content).includes('No activity recorded for this day.'))})
test('partial photo failure completion reports unavailable count',async()=>{const f=controllerFixture({readProof:async()=>{throw Error('private')}});await f.c.run('pdf',true);assert.match(f.state.notice,/1 activity photo/);assert.equal(f.calls.at(-1)[0],'save')})
test('Print cancel removes the private frame before opening dialog',async()=>{const f=fakeDocument(),p=await prepareJournalExport(report(),options()),abort=new AbortController();const pending=printJournalReport(p,abort.signal,f.parent);abort.abort();await assert.rejects(pending,/CANCELLED/);assert.equal(f.removed(),1);assert.equal(f.printed(),0)})
test('source projection omits attendance evidence even when input contains it',async()=>{const r=report();r.days[0].sessions[0].selfie='PRIVATE-SELFIE';r.days[0].sessions[0].latitude=14;r.days[0].sessions[0].address='PRIVATE-ADDRESS';const p=await prepareJournalExport(r,options({includePhotos:false}));assert.doesNotMatch(JSON.stringify(p),/PRIVATE-SELFIE|PRIVATE-ADDRESS|latitude/);assert.doesNotMatch(JSON.stringify(buildJournalPdf(p)),/PRIVATE-PATH/)})
test('download URL gets cleanup and Print never uses innerHTML or public routes',async()=>{const adapter=await readFile('src/services/journalExport.js','utf8'),print=await readFile('src/services/journalPrint.js','utf8');assert.match(adapter,/URL.revokeObjectURL/);assert.match(adapter,/link.remove\(\)/);assert.match(adapter,/reader.cancel\(\)/);assert.doesNotMatch(print,/innerHTML|document.write|window.open|http[s]?:\/\//);assert.match(print,/frame.remove\(\)/)})

test('mixed range Print retains each empty date and attendance',async()=>{const r=report();r.range.to='2026-10-06';r.days.push({...r.days[0],date:'2026-10-05',activities:[]},{date:'2026-10-06',activities:[],sessions:[],completedSeconds:0});const p=await prepareJournalExport(r,options({includePhotos:false})),f=fakeDocument();await printJournalReport(p,new AbortController().signal,f.parent);assert.equal(f.all.filter(n=>n.textContent==='No activity recorded for this day.').length,2);assert.ok(f.all.some(n=>n.textContent.includes('October 6, 2026')));assert.equal(p.days[1].sessions.length,2)})
