import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { SourceTextModule,SyntheticModule } from 'node:vm'
import { parse,compileTemplate } from '@vue/compiler-sfc'
import * as vue from 'vue'
import { renderToString } from '@vue/server-renderer'
import * as icons from 'lucide-vue-next'
import { createJournalProofReader,createJournalProofController,journalProofState } from '../src/services/journalProofController.js'
const blob=new Blob(['synthetic image'],{type:'image/png'})
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject}}
function fixture(){const state=journalProofState(),calls=[],revoked=[];let path='own/current-proof',identity='student',urls=0;const controller=createJournalProofController(state,{read:async(p)=>{calls.push(p);return blob},association:()=>path,identity:()=>identity,urls:{createObjectURL:()=>`blob:${++urls}`,revokeObjectURL:u=>revoked.push(u)}});return {state,calls,revoked,controller,path:p=>path=p,account:k=>identity=k}}
test('correct exact association retrieved and temporary image URL displayed',async()=>{const f=fixture();await f.controller.show();assert.deepEqual(f.calls,['own/current-proof']);assert.equal(f.state.url,'blob:1')})
test('visible proof retained; repeated show does not download again',async()=>{const f=fixture();await f.controller.show();await f.controller.show();assert.equal(f.calls.length,1)})
test('hide/scope/unmount cleanup revokes URL exactly once',async()=>{const f=fixture();await f.controller.show();f.controller.clear();f.controller.clear();assert.deepEqual(f.revoked,['blob:1']);assert.equal(f.state.url,'')})
test('new proof after replacement uses new association',async()=>{const f=fixture();await f.controller.show();f.path('own/replacement');f.controller.clear();await f.controller.show();assert.deepEqual(f.calls,['own/current-proof','own/replacement']);assert.equal(f.state.url,'blob:2')})
test('slow request exposes loading and coalesces repeat clicks',async()=>{const state=journalProofState(),gate=deferred();let calls=0;const c=createJournalProofController(state,{read:()=>{calls++;return gate.promise},association:()=> 'own',identity:()=> 'student',urls:{createObjectURL:()=> 'blob:ok',revokeObjectURL(){}}});const pending=c.show();assert.equal(state.loading,true);await c.show();assert.equal(calls,1);gate.resolve(blob);await pending;assert.equal(state.loading,false)})
test('cancelled slow request never creates URL',async()=>{const state=journalProofState(),gate=deferred();let creates=0;const c=createJournalProofController(state,{read:()=>gate.promise,association:()=> 'own',identity:()=> 'student',urls:{createObjectURL(){creates++;return 'blob:late'},revokeObjectURL(){}}});const pending=c.show();c.clear();gate.resolve(blob);await pending;assert.equal(creates,0);assert.equal(state.url,'')})
test('account or path change suppresses stale image even before watcher cleanup',async()=>{for(const change of ['account','path']){const state=journalProofState(),gate=deferred();let key='student',path='old';const c=createJournalProofController(state,{read:()=>gate.promise,association:()=>path,identity:()=>key,urls:{createObjectURL:()=> 'blob:leak',revokeObjectURL(){}}});const pending=c.show();if(change==='account')key='other';else path='new';gate.resolve(blob);await pending;assert.equal(state.url,'')}})
test('failed proof sanitized independently and deliberate retry succeeds',async()=>{const state=journalProofState();let fail=true;const c=createJournalProofController(state,{read:async()=>{if(fail)throw Error('PRIVATE PATH / RAW JWT');return blob},association:()=> 'own',identity:()=> 'student',urls:{createObjectURL:()=> 'blob:ok',revokeObjectURL(){}}});await c.show();assert.match(state.error,/unavailable/);assert.doesNotMatch(state.error,/PRIVATE|JWT/);fail=false;await c.show();assert.equal(state.url,'blob:ok');assert.equal(state.error,'')})
test('no proof or unapproved identity starts no retrieval',async()=>{for(const [path,key] of [['','student'],['own','']]){let calls=0;const c=createJournalProofController(journalProofState(),{read:()=>{calls++},association:()=>path,identity:()=>key});await c.show();assert.equal(calls,0)}})
test('reader authenticates, downloads then validates raw bytes without DOM coupling',async()=>{const calls=[];const reader=createJournalProofReader({download:async p=>{calls.push(p);return blob},validate:async b=>{assert.equal(b,blob);calls.push('validate')},identity:()=> 'approved'});assert.equal(await reader.read('exact/reference'),blob);assert.deepEqual(calls,['exact/reference','validate'])})
test('reader enforces two concurrent downloads for many activities',async()=>{const gates=[];let active=0,max=0;const reader=createJournalProofReader({identity:()=> 'student',validate:async()=>{},download:()=>{active++;max=Math.max(max,active);const d=deferred();gates.push(d);return d.promise.finally(()=>active--)}});const jobs=Array.from({length:8},(_,i)=>reader.read(`own/${i}`));await new Promise(r=>setImmediate(r));assert.equal(gates.length,2);for(let i=0;i<8;i++){gates[i].resolve(blob);await new Promise(r=>setImmediate(r))}await Promise.all(jobs);assert.equal(max,2)})
test('cancelled queued proof never dispatched',async()=>{const gate=deferred(),calls=[];const reader=createJournalProofReader({concurrency:1,identity:()=> 'student',validate:async()=>{},download:p=>{calls.push(p);return gate.promise}});const first=reader.read('one'),abort=new AbortController(),second=reader.read('two',abort.signal);abort.abort();await assert.rejects(second,/CANCELLED/);gate.resolve(blob);await first;assert.deepEqual(calls,['one'])})
test('reader discards account-changed bytes and invalid blobs',async()=>{let key='student';const gate=deferred();const reader=createJournalProofReader({identity:()=>key,download:()=>gate.promise,validate:async()=>{}});const pending=reader.read('own');await new Promise(r=>setImmediate(r));key='other';gate.resolve(blob);await assert.rejects(pending,/CANCELLED/);const bad=createJournalProofReader({identity:()=> 'student',download:async()=>blob,validate:async()=>{throw Error('INVALID_PROOF')}});await assert.rejects(bad.read('own'),/INVALID_PROOF/)})
test('one failed image does not block other readers',async()=>{const reader=createJournalProofReader({identity:()=> 'student',download:async p=>{if(p==='bad')throw Error('unavailable');return blob},validate:async()=>{}});const results=await Promise.allSettled([reader.read('bad'),reader.read('good')]);assert.equal(results[0].status,'rejected');assert.equal(results[1].status,'fulfilled')})
const filename='src/components/JournalActivityProof.vue',source=await readFile(filename,'utf8'),{descriptor}=parse(source),template=compileTemplate({source:descriptor.template.content,filename,id:'proof-test'});assert.deepEqual(template.errors,[])
const componentModule=new SourceTextModule(descriptor.script.content+'\n'+template.code)
function synthetic(values){return new SyntheticModule(Object.keys(values),function(){for(const [k,v]of Object.entries(values))this.setExport(k,v)})}
let network=0
await componentModule.link(s=>{if(s==='vue')return synthetic(vue);if(s==='lucide-vue-next')return synthetic(icons);if(s.endsWith('journalActivityProof.js'))return synthetic({journalProofIdentity:()=> 'student',readJournalActivityProof:()=>{network++;return Promise.resolve(blob)}});if(s.endsWith('supabaseActivities.js'))return synthetic({activityAccountKey:()=> 'student'});if(s.endsWith('journalProofController.js'))return synthetic({journalProofState,createJournalProofController});throw Error(s)})
await componentModule.evaluate();const component=componentModule.namespace.default;component.render=componentModule.namespace.render
async function render(proof,path='PRIVATE-PATH'){return renderToString(vue.createSSRApp({...component,data(){return {proof,controller:null}}},{path}))}
test('successful inline image contains aspect ratio, alt and hide control, no private path',async()=>{const html=await render({url:'blob:temporary',loading:false,error:''});assert.match(html,/<img/);assert.match(html,/object-contain/);assert.match(html,/max-h-80/);assert.match(html,/Recorded activity proof photo/);assert.match(html,/Hide photo/);assert.doesNotMatch(html,/PRIVATE-PATH/);assert.equal(network,0)})
test('independent loading, retry and no-proof UI',async()=>{assert.match(await render({url:'',loading:true,error:''}),/Loading proof photo/);assert.match(await render({url:'',loading:false,error:'Proof photo unavailable. Please try again.'}),/Retry proof photo/);assert.match(await render(journalProofState(),''),/No proof photo available/);assert.equal(network,0)})
test('component lifecycle wires path/account/unmount cleanup and image decode failure',()=>{let clears=0;const vm={controller:{clear(){clears++}},proof:journalProofState()};component.watch.path.call(vm);component.watch.accountKey.call(vm);component.beforeUnmount.call(vm);component.methods.imageFailed.call(vm);assert.equal(clears,4);assert.match(vm.proof.error,/unavailable/)})
test('Journal uses trusted source association and no attendance/AI/external image retrieval',async()=>{const journal=await readFile('src/views/student/JournalView.vue','utf8'),adapter=await readFile('src/services/journalActivityProof.js','utf8');assert.match(journal,/internal.sources\[activity.sourceIndex\]/);assert.match(journal,/<JournalActivityProof :path="proofPath\(activity\)"/);assert.match(adapter,/activityApi.download\(path\)/);assert.match(adapter,/validate: validatePhoto/);assert.doesNotMatch(adapter,/attendance|fetch\(|https:|getPublicUrl|createSignedUrl|functions\.invoke|Groq|Cloudflare|service.role/i)})
