import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile, writeFile } from 'node:fs/promises'
// JSZip is a pinned docx transitive dependency; used only to inspect our output.
import JSZip from 'jszip'
import path from 'node:path'
import { generateJournalDocx } from '../src/services/journalDocx.js'
import { prepareJournalExport, exportFilename } from '../src/services/journalExportModel.js'
import { createJournalExportController, journalExportState } from '../src/services/journalExportController.js'
import { convertJournalImage } from '../src/services/journalExportImages.js'
const description='  Installed RAM & checked <records>.\nRésumé señor 日本語 😀\tExact CASE!  '
const image=await readFile(new URL('./helpers/journalExportProof.png',import.meta.url))
const photo={data:'data:image/png;base64,'+image.toString('base64'),width:640,height:320,bytes:image.length}
function report(){return {student:{fullName:'Synthetic Student',studentId:'S/01',program:'BSIT',requiredHours:486},range:{from:'2026-10-04',to:'2026-10-06'},days:[{date:'2026-10-04',activities:[{sourceIndex:0,createdAt:'2026-10-04T00:00:00Z',category:'IT Support',description,edited:true}],sessions:[{ordinal:1,timeIn:'2026-10-04T00:00:00Z',timeOut:'2026-10-04T01:00:00Z'},{ordinal:2,timeIn:'2026-10-04T15:00:00Z',timeOut:null}],completedSeconds:3600},{date:'2026-10-05',activities:[],sessions:[{ordinal:1,timeIn:'2026-10-05T00:00:00Z',timeOut:'2026-10-05T01:00:00Z'}],completedSeconds:3600},{date:'2026-10-06',activities:[],sessions:[],completedSeconds:0}],selectedRangeCompletedSeconds:7200,lifetimeCompletedSeconds:10800,internal:{sources:[{proofPath:'PRIVATE-PATH',id:'PRIVATE-ID',revision:0}]}}}
const options=(extra={})=>({readProof:async()=>new Blob([image]),convertImage:async()=>photo,...extra})
async function inspect(blob){
 const data=Buffer.from(await blob.arrayBuffer());assert.equal(data.subarray(0,2).toString(),'PK')
 const zip=await JSZip.loadAsync(data),names=Object.keys(zip.files)
 const decode=text=>text.replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,'&')
 for(const name of names.filter(n=>n.endsWith('.rels'))){const xml=await zip.file(name).async('string');assert.doesNotMatch(xml,/TargetMode="External"/);const folder=name==='_rels/.rels'?'':path.posix.dirname(path.posix.dirname(name));for(const match of xml.matchAll(/Target="([^"]+)"/g))assert.ok(names.includes(path.posix.normalize(path.posix.join(folder,decode(match[1])))),match[1])}
 const xml=await zip.file('word/document.xml').async('string'),paragraphs=[]
 for(const p of xml.matchAll(/<w:p(?:\s[^>]*)?>([\s\S]*?)<\/w:p>/g)){let text='';for(const part of p[1].matchAll(/<w:t(?:\s[^>]*)?>([\s\S]*?)<\/w:t>|<w:br\b[^>]*\/>|<w:tab\b[^>]*\/>/g))text+=part[1]!==undefined?decode(part[1]):part[0].startsWith('<w:br')?'\n':'\t';paragraphs.push(text)}
 const media={};for(const name of names.filter(n=>n.startsWith('word/media/')&&!zip.files[n].dir))media[name]=await zip.file(name).async('base64')
 return {names,paragraphs,xml,media}
}
const prepared=await prepareJournalExport(report(),options())
const blob=await generateJournalDocx(prepared)
const pkg=await inspect(blob)
await writeFile('/tmp/dtr-u64e-synthetic.docx',Buffer.from(await blob.arrayBuffer()))
test('genuine OOXML package, relationships and editable Word text',()=>{for(const name of ['[Content_Types].xml','_rels/.rels','word/document.xml','word/_rels/document.xml.rels'])assert.ok(pkg.names.includes(name));assert.ok(pkg.xml.includes('<w:t xml:space="preserve">'));assert.doesNotMatch(pkg.xml,/altChunk|PRIVATE-PATH|PRIVATE-ID|selfie|latitude|longitude/);assert.ok(pkg.paragraphs.includes(description))})
test('metadata and all authoritative hours remain distinct',()=>{const text=pkg.paragraphs.join('\n');for(const value of ['Synthetic Student','Student ID: S/01','Program: BSIT','Required OJT Hours: 486','Selected Journal Completed Hours: 2h 00m','Total Completed OJT Hours (all dates): 3h 00m','Asia/Manila'])assert.ok(text.includes(value))})
test('chronological dates, exact empty wording and attendance-only date retained',()=>{const text=pkg.paragraphs.join('\n');assert.ok(text.indexOf('October 4, 2026 · Completed:')<text.indexOf('October 5, 2026 · Completed:'));assert.ok(text.indexOf('October 5, 2026 · Completed:')<text.indexOf('October 6, 2026 · Completed:'));assert.equal(pkg.paragraphs.filter(p=>p==='No activity recorded for this day.').length,2);assert.ok(text.includes('Attendance summary · October 5, 2026'));assert.ok(text.includes('Ongoing'));assert.ok(pkg.paragraphs.includes('2'))})
test('PNG actual bytes embedded with preserved aspect ratio and A4 dimensions',()=>{assert.ok(Object.values(pkg.media).includes(image.toString('base64')));assert.match(pkg.xml,/cx="5143500" cy="2571750"/);assert.match(pkg.xml,/w:w="11906" w:h="16838"/);assert.match(pkg.xml,/Edited/)})
test('Daily and range DOCX names reuse safe PDF naming; PDF unchanged',()=>{const r=report();assert.equal(exportFilename(r,'docx'),'OJT-Journal_S_01_2026-10-04_to_2026-10-06.docx');assert.equal(exportFilename(r),'OJT-Journal_S_01_2026-10-04_to_2026-10-06.pdf');r.range.to=r.range.from;assert.equal(exportFilename(r,'docx'),'OJT-Journal_S_01_2026-10-04.docx')})
test('zero Activity rejects direct DOCX generation',async()=>{await assert.rejects(generateJournalDocx({days:[{activities:[]}]}),/JOURNAL_NO_ACTIVITIES/)})
test('photos OFF has no private reads and no media in genuine DOCX',async()=>{let reads=0;const p=await prepareJournalExport(report(),options({includePhotos:false,readProof:()=>{reads++}}));const zip=await inspect(await generateJournalDocx(p));assert.equal(reads,0);assert.equal(Object.keys(zip.media).length,0);assert.ok(zip.paragraphs.includes(description))})
test('multiple photo association and preparation stay sequential',async()=>{const r=report();r.days[0].activities.push({...r.days[0].activities[0],sourceIndex:1,description:'Second task'});r.internal.sources.push({proofPath:'SECOND-PATH'});let active=0,max=0;const paths=[];const p=await prepareJournalExport(r,options({readProof:async path=>{paths.push(path);active++;max=Math.max(max,active);await new Promise(resolve=>setImmediate(resolve));active--;return new Blob([image])}}));const zip=await inspect(await generateJournalDocx(p));assert.deepEqual(paths,['PRIVATE-PATH','SECOND-PATH']);assert.equal(max,1);assert.equal((zip.xml.match(/<w:drawing>/g)||[]).length,2);assert.ok(zip.paragraphs.indexOf(description)<zip.paragraphs.indexOf('Second task'))})
test('unavailable proof still generates editable activity document',async()=>{const p=await prepareJournalExport(report(),options({readProof:async()=>{throw Error('PRIVATE-PATH')}}));const zip=await inspect(await generateJournalDocx(p));assert.ok(zip.paragraphs.includes(description));assert.ok(zip.paragraphs.includes('Activity proof photo unavailable'));assert.doesNotMatch(zip.xml,/PRIVATE-PATH/)})
function fixture(extra={}){let r=report(),identity='student';const state=journalExportState(),calls=[];const c=createJournalExportController(state,{currentReport:()=>r,identity:()=>identity,...options(),validateReport:async()=>r,docx:async p=>{calls.push(p);return blob},save:async(b,name)=>calls.push(name),...extra});return {c,state,calls,change:()=>{r=report()},account:()=>{identity='other'}}}
test('DOCX controller uses same preparation and safe save path',async()=>{const f=fixture();await f.c.run('docx',true);assert.ok(f.calls[0].days[0].activities[0].photo);assert.match(f.calls[1],/\.docx$/);assert.equal(f.state.notice,'Word document generated.')})
test('DOCX duplicate generation blocked',async()=>{let release,calls=0;const f=fixture({docx:()=>{calls++;return new Promise(resolve=>release=resolve)}});const pending=f.c.run('docx',false);await new Promise(r=>setImmediate(r));await f.c.run('docx',false);release(blob);await pending;assert.equal(calls,1);assert.equal(f.calls.length,1)})
test('DOCX cancellation scope and account change suppress late save',async()=>{for(const change of ['cancel','change','account']){let release;const f=fixture({docx:()=>new Promise(resolve=>release=resolve)});const pending=f.c.run('docx',false);await new Promise(r=>setImmediate(r));if(change==='cancel')f.c.cancel();else f[change]();release(blob);await pending;assert.equal(f.calls.length,0)}})
test('revision recheck and limits unchanged for DOCX',async()=>{const f=fixture({validateReport:async()=>({...report(),lifetimeCompletedSeconds:999})});await f.c.run('docx',false);assert.match(f.state.error,/Records changed/);assert.equal(f.calls.length,0);const r=report();r.days[0].activities=Array.from({length:501},()=>r.days[0].activities[0]);await assert.rejects(prepareJournalExport(r,options({includePhotos:false})),/EXPORT_TOO_LARGE/)})
test('DOCX lazy import, private adapter and no external services',async()=>{const s=await readFile('src/services/journalDocx.js','utf8'),adapter=await readFile('src/services/journalExport.js','utf8');assert.match(s,/await import\('docx'\)/);assert.match(adapter,/docx: generateJournalDocx/);assert.match(adapter,/readProof: readJournalActivityProof/);assert.doesNotMatch(s,/fetch\(|https?:\/\/|getPublicUrl|createSignedUrl|innerHTML|Groq|Cloudflare|service.role/i)})
test('JPEG and WebP inputs use same local JPEG conversion accepted by DOCX',async()=>{
 const originals={Image:globalThis.Image,document:globalThis.document,create:URL.createObjectURL,revoke:URL.revokeObjectURL};let revocations=0
 const jpeg=await readFile(new URL('./helpers/journalExportProof.jpg',import.meta.url))
 try{globalThis.Image=class{naturalWidth=640;naturalHeight=320;set src(_){queueMicrotask(()=>this.onload())}};globalThis.document={createElement:()=>({getContext:()=>({fillRect(){},drawImage(){}}),toDataURL:type=>{assert.equal(type,'image/jpeg');return 'data:image/jpeg;base64,'+jpeg.toString('base64')}})};URL.createObjectURL=()=> 'blob:local';URL.revokeObjectURL=()=>revocations++
 for(const type of ['image/jpeg','image/png','image/webp']){const converted=await convertJournalImage(new Blob(['synthetic'],{type}));const p=structuredClone(prepared);p.days[0].activities[0].photo=converted;const zip=await inspect(await generateJournalDocx(p));assert.ok(Object.values(zip.media).includes(jpeg.toString('base64')));assert.equal(converted.width/converted.height,2)}assert.equal(revocations,3)
 }finally{globalThis.Image=originals.Image;globalThis.document=originals.document;URL.createObjectURL=originals.create;URL.revokeObjectURL=originals.revoke}
})
test('XML-incompatible text explicitly rejected without rewriting entries',async()=>{const p=structuredClone(prepared);p.days[0].activities[0].description='bad\u0000entry';await assert.rejects(generateJournalDocx(p),/DOCX_UNSUPPORTED_TEXT/);assert.equal(p.days[0].activities[0].description,'bad\u0000entry')})
