import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { buildJournalReport,journalCompletePeriod,journalRange,canExportJournal,COMPLETE_JOURNAL_LIMITS } from '../src/services/journalReportModel.js'
import { createJournalReader } from '../src/services/journalReportService.js'
import { journalPageState,createJournalPageController } from '../src/services/journalPageController.js'
import { prepareJournalExport,buildJournalPdf,exportFilename } from '../src/services/journalExportModel.js'
import { createJournalExportController,journalExportState } from '../src/services/journalExportController.js'
const profile={fullName:'Student',studentId:'S01',program:'BSIT',requiredHours:486}
const activity=(id,time='2026-08-03T00:00:00Z')=>({id,created_at:time,category:'Other',description:'  Exact résumé!\nSecond line.  ',revision:0,updated_at:null,photo_path:'PRIVATE-PATH/'+id,attendance_session_id:'session'})
const attendance={start_day:'2026-10-05',completed_seconds:501*3600+16*60,sessions:[{id:'session',session_ordinal:1,time_in:'2026-10-05T00:00:00Z',time_out:'2026-10-25T21:16:00Z',completed_seconds:501*3600+16*60}]}
function fixture(extra={}){let key='student';const reader=createJournalReader({identity:()=>key,profile:async()=>profile,summary:async()=>({completed_seconds:attendance.completed_seconds}),completePeriod:async()=>({from:'2026-08-03',to:'2026-10-05'}),completeActivityPage:async()=>({activities:[activity('a')],next:null}),completeAttendancePage:async()=>({days:[attendance],next_before_day:null}),activityPage:()=>{throw Error('range path')},attendancePage:()=>{throw Error('range path')},...extra});return {reader,account:()=>{key='other'}}}
test('Complete uses distinct bounded contract; 31-day range still rejects',()=>{assert.equal(journalCompletePeriod('2026-08-03','2026-10-05').dates.length,64);assert.throws(()=>journalRange('2026-08-03','2026-10-05'));assert.deepEqual(journalCompletePeriod(null,null).dates,[]);assert.throws(()=>journalCompletePeriod(null,'2026-10-05'));assert.throws(()=>journalCompletePeriod('2000-01-01','2026-10-05'),/TOO_LARGE/);assert.equal(COMPLETE_JOURNAL_LIMITS.activities,10000)})
test('complete report chronological continuity, attendance-only/empty dates and hours above requirement',async()=>{const r=await fixture().reader.prepareComplete();assert.equal(r.days.length,64);assert.equal(r.range.scope,'complete');assert.equal(r.days[0].activities.length,1);assert.equal(r.days[1].activities.length,0);assert.equal(r.days[1].sessions.length,0);assert.equal(r.days.at(-1).sessions.length,1);assert.equal(r.days[0].activities[0].description,activity('a').description);assert.ok(r.selectedRangeCompletedSeconds>486*3600);assert.equal(r.selectedRangeCompletedSeconds,r.lifetimeCompletedSeconds);assert.equal(canExportJournal(r),true)})
test('no records means no invented boundaries or export',async()=>{const r=await fixture({summary:async()=>({completed_seconds:0}),completePeriod:async()=>({from:null,to:null}),completeActivityPage:()=>{throw Error('no pages expected')}}).reader.prepareComplete();assert.equal(r.range.from,null);assert.equal(r.days.length,0);assert.equal(canExportJournal(r),false)})
test('attendance-only Complete remains viewable and ineligible',async()=>{const r=await fixture({completeActivityPage:async()=>({activities:[],next:null})}).reader.prepareComplete();assert.equal(r.days.at(-1).sessions.length,1);assert.equal(canExportJournal(r),false)})
test('hundreds of Activities fetch every bounded cursor page with no UID/date arguments',async()=>{const rows=Array.from({length:305},(_,i)=>activity(String(i).padStart(4,'0'),new Date(Date.parse('2026-08-03T00:00:00Z')+i*1000).toISOString()));let calls=0;const r=await fixture({completeActivityPage:async args=>{calls++;assert.equal(args.page_size,100);assert.equal(Object.hasOwn(args,'from_day'),false);assert.equal(Object.hasOwn(args,'student_uid'),false);const offset=args.after_id===null?0:Number(args.after_id)+1,items=rows.slice(offset,offset+100);return {activities:items,next:offset+100<rows.length?{id:items.at(-1).id,created_at:items.at(-1).created_at}:null}}}).reader.prepareComplete();assert.equal(r.internal.sources.length,305);assert.equal(calls,4)})
test('multiple Attendance pages consumed with strict descending cursor',async()=>{let calls=0;const r=await fixture({completeAttendancePage:async args=>{calls++;if(args.before_day===null)return {days:[attendance],next_before_day:'2026-10-05'};assert.equal(args.before_day,'2026-10-05');return {days:[{start_day:'2026-08-03',completed_seconds:0,sessions:[{id:'open',session_ordinal:1,time_in:'2026-08-03T00:00:00Z',time_out:null,completed_seconds:0}]}],next_before_day:null}}}).reader.prepareComplete();assert.equal(calls,2);assert.equal(r.days[0].sessions[0].timeOut,null)})
test('failed page rejects rather than returning partial history',async()=>{let n=0;await assert.rejects(fixture({completeActivityPage:async()=>{if(n++)throw Error('offline');return {activities:[activity('a')],next:{id:'a',created_at:activity('a').created_at}}}}).reader.prepareComplete(),/offline/)})
test('invalid/repeated cursor and nonchronological records rejected',async()=>{for(const page of [{activities:[activity('a')],next:{id:'foreign',created_at:activity('a').created_at}},{activities:[activity('b'),activity('a')],next:null}])await assert.rejects(fixture({completeActivityPage:async()=>page}).reader.prepareComplete(),/INVALID_JOURNAL_PAGE/)})
test('new boundaries or mismatched totals refuse inconsistent complete load',async()=>{let n=0;await assert.rejects(fixture({completePeriod:async()=>++n===1?{from:'2026-08-03',to:'2026-10-05'}:{from:'2026-08-03',to:'2026-10-06'}}).reader.prepareComplete(),/CHANGED/);await assert.rejects(fixture({summary:async()=>({completed_seconds:1})}).reader.prepareComplete(),/CHANGED/)})
test('Complete cancellation and account change discard late read',async()=>{for(const action of ['cancel','account']){let release;const f=fixture({completePeriod:()=>new Promise(resolve=>release=resolve)});const pending=f.reader.prepareComplete();await new Promise(r=>setImmediate(r));if(action==='cancel')f.reader.cancel();else f.account();release({from:'2026-08-03',to:'2026-10-05'});await assert.rejects(pending,/CANCELLED|ACCOUNT_CHANGED/)}})
test('new Daily request wins over stale Complete scope response',async()=>{let release;const state=journalPageState();state.mode='complete';const c=createJournalPageController(state,{cancel(){},prepareComplete:()=>new Promise(resolve=>release=resolve),prepare:async()=>({scope:'daily'})},()=>true);const pending=c.load();state.mode='daily';await c.load();release({scope:'complete'});await pending;assert.equal(state.report.scope,'daily')})
test('Complete controller ignores manual dates and uses approved load method',async()=>{const state={...journalPageState(),mode:'complete',from:'bad',to:'bad'};let calls=0;await createJournalPageController(state,{cancel(){},prepareComplete:async()=>{calls++;return {range:{scope:'complete'}}},prepare(){throw Error('range')}},()=>true).load();assert.equal(calls,1);assert.equal(state.report.range.scope,'complete')})
test('all existing exporters receive same Complete facts and naming',async()=>{const r=await fixture().reader.prepareComplete();for(const kind of ['pdf','docx','print']){let reads=0,prepared;const state=journalExportState(),c=createJournalExportController(state,{currentReport:()=>r,identity:()=> 'student',readProof:()=>{reads++;throw Error('OFF')},convertImage(){throw Error('OFF')},validateReport:async range=>{assert.equal(range.scope,'complete');return r},pdf:async p=>{prepared=p;return new Blob(['pdf'])},docx:async p=>{prepared=p;return new Blob(['docx'])},print:async p=>{prepared=p},save:async(b,name)=>assert.match(name,/Complete-OJT_2026-08-03_to_2026-10-05/)});await c.run(kind,false);assert.equal(state.error,'');assert.equal(reads,0);assert.equal(prepared.days.length,64);assert.match(prepared.selectedDates,/Complete OJT/);assert.equal(prepared.days[0].activities[0].description,activity('a').description);assert.ok(JSON.stringify(buildJournalPdf(prepared)).includes('No activity recorded for this day.'))}})
test('Complete photo limit explicitly refuses; OFF bypasses photo reads without dropping Activities',async()=>{const r=await fixture().reader.prepareComplete();const source=r.days[0].activities[0];r.days[0].activities=Array.from({length:101},()=>source);await assert.rejects(prepareJournalExport(r,{includePhotos:true}),/EXPORT_TOO_LARGE/);const p=await prepareJournalExport(r,{includePhotos:false});assert.equal(p.days[0].activities.length,101);assert.equal(exportFilename(r,'docx'),'OJT-Journal_S01_Complete-OJT_2026-08-03_to_2026-10-05.docx')})
test('adapter calls Complete RPCs, final export validates Complete scope, no Storage/provider paths',async()=>{const adapter=await readFile('src/services/supabaseJournal.js','utf8');for(const rpc of ['journal_complete_period','journal_complete_activities','journal_complete_attendance'])assert.ok(adapter.includes(rpc));assert.doesNotMatch(adapter,/\.storage|service_role|functions.invoke|Groq|Cloudflare/);assert.match(await readFile('src/services/journalExport.js','utf8'),/range.scope === 'complete' \? reader.prepareComplete\(\)/)})
test('Activity read ceiling fails explicitly instead of truncating',async()=>{const rows=Array.from({length:10001},(_,i)=>activity(String(i).padStart(5,'0'),new Date(Date.parse('2026-08-03T00:00:00Z')+i*1000).toISOString()));await assert.rejects(fixture({completeActivityPage:async args=>{const offset=args.after_id===null?0:Number(args.after_id)+1,items=rows.slice(offset,offset+100);return {activities:items,next:offset+100<rows.length?{id:items.at(-1).id,created_at:items.at(-1).created_at}:null}}}).reader.prepareComplete(),/JOURNAL_COMPLETE_TOO_LARGE/)})
test('real PDF and genuine DOCX generators accept Complete period beyond 31 dates',async()=>{const r=await fixture().reader.prepareComplete(),prepared=await prepareJournalExport(r,{includePhotos:false});const {generateJournalPdf}=await import('../src/services/journalPdf.js'),{generateJournalDocx}=await import('../src/services/journalDocx.js'),{default:JSZip}=await import('jszip');const pdf=await generateJournalPdf(prepared);assert.equal(Buffer.from(await pdf.arrayBuffer()).subarray(0,5).toString(),'%PDF-');const docx=await generateJournalDocx(prepared),zip=await JSZip.loadAsync(await docx.arrayBuffer()),xml=await zip.file('word/document.xml').async('string');assert.ok(xml.includes('Complete OJT'));assert.ok(xml.includes('October 5, 2026'));assert.equal((xml.match(/No activity recorded for this day\./g)||[]).length,63);assert.ok(xml.includes('501h 16m'))})

test('total Complete read budget rejects explicitly and leaves no partial report',async()=>{const original=Date.now;let now=0;try{Date.now=()=>{now+=30000;return now};await assert.rejects(fixture().reader.prepareComplete(),/JOURNAL_COMPLETE_TOO_LARGE/)}finally{Date.now=original}})
